apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: aws-eu-central-1
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: upbound-system
      name: tf-aws-creds
      key: credentials
